DROP PROCEDURE IF EXISTS ROWPERROW;
DELIMITER ;;

CREATE PROCEDURE ROWPERROW()
	BEGIN
	DECLARE n INT DEFAULT 0;
	DECLARE i INT DEFAULT 0;
	SELECT COUNT(*) FROM (VALUES ROW (1000), ROW (2000), ROW (3000)) AS MassListTable INTO n;
	SET i=0;
	WHILE i<n DO 
	  SELECT 'comment';
	END WHILE;
	END;
	;;